### ISSUE TITLE
[bug] TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by SuperOleg39** [Tinkoff/linters#115] opened 2021-08-12 09:44 UTC
## Reproduce

install dependencies:
```
npm i @tinkoff/eslint-config @tinkoff/eslint-config-react @tinkoff/eslint-plugin-tramvai
```

modyfy `.eslintrc`:
```
module.exports = {
    extends: [
        '@tinkoff/eslint-config/app',
        '@tinkoff/eslint-config/jest',
        '@tinkoff/eslint-config-react',
        'plugin:@tinkoff/tramvai/recommended',
    ],
    rules: {
        '@typescript-eslint/naming-convention': 1,
    },
};
```

add destructurisation in `js` file:
```
const x = ({ ...y }) => {}
```

## Error

```
TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/b.ponomarenko/Desktop/es-app/index.js:1
    at getIdentifiersFromPattern (/Users/b.ponomarenko/Desktop/es-app/node_modules/@typescript-eslint/eslint-plugin/dist/rules/naming-convention.js:532:21)
    at /Users/b.ponomarenko/Desktop/es-app/node_modules/@typescript-eslint/eslint-plugin/dist/rules/naming-convention.js:553:21
    at Array.forEach (<anonymous>)
    at getIdentifiersFromPattern (/Users/b.ponomarenko/Desktop/es-app/node_modules/@typescript-eslint/eslint-plugin/dist/rules/naming-convention.js:544:32)
    at /Users/b.ponomarenko/Desktop/es-app/node_modules/@typescript-eslint/eslint-plugin/dist/rules/naming-convention.js:397:21
    at Array.forEach (<anonymous>)
    at FunctionDeclaration, TSDeclareFunction, FunctionExpression, ArrowFunctionExpression (/Users/b.ponomarenko/Desktop/es-app/node_modules/@typescript-eslint/eslint-plugin/dist/rules/naming-convention.js:392:29)
    at /Users/b.ponomarenko/Desktop/es-app/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/b.ponomarenko/Desktop/es-app/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

## Problem

Error only with enabled `@typescript-eslint/naming-convention` rule

**Comment by adi-uchiha** [comment] 2022-09-30 10:23
hey there. I am new to open source and I want to fix this issue for Hacktoberfest.
Can you assign this to me.

**Comment by splincode** [comment] 2022-10-02 16:13
@adi-uchiha done :)

**Comment by adi-uchiha** [comment] 2022-10-02 19:16
I can not even reproduce this error. I think I am unexperienced for this

**Comment by zlodeev** [comment] 2022-10-10 13:20
Rare, can't reproduce

I think it's fixed by `eslint-plugin` already. All strings from stacktrace are missing lines in the current version of package. 

Error borned in `FunctionDeclaration` and have only one entry with access to param `type` at

https://github.com/typescript-eslint/typescript-eslint/blob/ac6ccda4e90cea2b16520f544b0999186b21d5d0/packages/eslint-plugin/src/rules/naming-convention.ts#L276-L279

**Comment by splincode** [comment] 2022-10-10 13:33
well, thanks for the investigation :)

**Closed by splincode** 2022-10-10 13:33 UTC
